package gr.pdfbookreader
import android.content.*; import android.net.Uri; import android.os.Bundle; import android.provider.OpenableColumns; import android.view.Gravity; import android.widget.*; import androidx.activity.result.contract.ActivityResultContracts; import androidx.appcompat.app.AppCompatActivity
class MainActivity:AppCompatActivity(){
 private lateinit var list:LinearLayout; private val prefs by lazy{getSharedPreferences("library",MODE_PRIVATE)}
 private val picker=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->u?.let{try{contentResolver.takePersistableUriPermission(it,Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};val n=fileName(it);val s=prefs.getStringSet("books",emptySet())!!.toMutableSet();s.add(it.toString()+"|"+n);prefs.edit().putStringSet("books",s).apply();showBooks();openBook(it,n)}}
 override fun onCreate(b:Bundle?){super.onCreate(b);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(36,48,36,24)};root.addView(TextView(this).apply{text="Η βιβλιοθήκη μου";textSize=28f;setPadding(0,0,0,24)});root.addView(Button(this).apply{text="+  Προσθήκη PDF";setOnClickListener{picker.launch(arrayOf("application/pdf"))}});list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(ScrollView(this).apply{addView(list)},LinearLayout.LayoutParams(-1,0,1f));setContentView(root);showBooks()}
 private fun showBooks(){list.removeAllViews();val bs=prefs.getStringSet("books",emptySet())!!.sorted();if(bs.isEmpty())list.addView(TextView(this).apply{text="Δεν έχεις προσθέσει βιβλία ακόμη.\n\nΠάτησε «Προσθήκη PDF» για να ξεκινήσεις.";textSize=18f;gravity=Gravity.CENTER;setPadding(20,100,20,20)});bs.forEach{x->val p=x.split("|",limit=2);val u=Uri.parse(p[0]);val n=p.getOrElse(1){"PDF"};list.addView(Button(this).apply{text="📖  $n";textSize=17f;isAllCaps=false;setOnClickListener{openBook(u,n)}},LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,14,0,0)})}}
 private fun openBook(u:Uri,n:String){startActivity(Intent(this,ReaderActivity::class.java).putExtra("uri",u.toString()).putExtra("name",n))}
 private fun fileName(u:Uri):String{var n="Βιβλίο.pdf";contentResolver.query(u,null,null,null,null)?.use{c->if(c.moveToFirst()){val i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)n=c.getString(i)}};return n.removeSuffix(".pdf")}
}