package gr.pdfbookreader
import android.graphics.*; import android.graphics.pdf.PdfRenderer; import android.net.Uri; import android.os.*; import android.view.*; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import kotlin.math.abs
class ReaderActivity:AppCompatActivity(){
 private var fd:ParcelFileDescriptor?=null;private var renderer:PdfRenderer?=null;private lateinit var image:ImageView;private lateinit var info:TextView;private var page=0;private var downX=0f;private lateinit var key:String;private val prefs by lazy{getSharedPreferences("progress",MODE_PRIVATE)}
 override fun onCreate(b:Bundle?){super.onCreate(b);window.statusBarColor=Color.BLACK;val u=Uri.parse(intent.getStringExtra("uri"));key=u.toString();val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(25,25,25))};val bar=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(12,8,12,8)};bar.addView(Button(this).apply{text="‹";textSize=25f;setOnClickListener{finish()}});info=TextView(this).apply{setTextColor(Color.WHITE);textSize=15f;gravity=Gravity.CENTER};bar.addView(info,LinearLayout.LayoutParams(0,-2,1f));image=ImageView(this).apply{setBackgroundColor(Color.rgb(35,35,35));scaleType=ImageView.ScaleType.FIT_CENTER};root.addView(bar);root.addView(image,LinearLayout.LayoutParams(-1,0,1f));setContentView(root)
 try{fd=contentResolver.openFileDescriptor(u,"r");renderer=PdfRenderer(fd!!);page=prefs.getInt(key,0).coerceIn(0,(renderer!!.pageCount-1).coerceAtLeast(0));image.setOnTouchListener{_,e->when(e.action){MotionEvent.ACTION_DOWN->{downX=e.x;true};MotionEvent.ACTION_UP->{val d=e.x-downX;if(abs(d)>80){if(d<0)next() else prev()};true};else->true}};image.post{render()}}catch(e:Exception){Toast.makeText(this,"Δεν ήταν δυνατό να ανοίξει το PDF",Toast.LENGTH_LONG).show();finish()}}
 private fun render(){val r=renderer?:return;if(r.pageCount==0)return;val p=r.openPage(page);val w=(image.width.takeIf{it>0}?:resources.displayMetrics.widthPixels).coerceAtLeast(600);val bmp=Bitmap.createBitmap(w,(w*p.height.toFloat()/p.width).toInt().coerceAtLeast(1),Bitmap.Config.ARGB_8888);bmp.eraseColor(Color.WHITE);p.render(bmp,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);p.close();image.setImageBitmap(bmp);info.text=(intent.getStringExtra("name")?:"PDF")+"     "+(page+1)+" / "+r.pageCount;prefs.edit().putInt(key,page).apply()}
 private fun next(){if(page<(renderer?.pageCount?:1)-1){page++;render()}};private fun prev(){if(page>0){page--;render()}}
 override fun onDestroy(){renderer?.close();fd?.close();super.onDestroy()}
}